Use permit
defi-wonderland/xTokens pull request #1
Opened 2023-08-17 20:48 UTC by just-a-node

Adds a `depositWithPermitAllowance` function to allow permit2-style transfers.

2023-08-21 15:15 UTC, 0xShaito requested changes

2023-08-21 15:15 UTC, 0xShaito commented on solidity/contracts/XERC20Lockbox.sol
> +    address _owner,
Why don't we use `msg.sender` instead of allowing an _owner parameter?

2023-08-21 15:15 UTC, 0xShaito commented on solidity/contracts/XERC20Lockbox.sol
> +   * @param _amount The amount of tokens to deposit
Lets fill in this natspec

2023-08-21 15:15 UTC, 0xShaito commented on solidity/contracts/XERC20Lockbox.sol
> +
Taken from the uniswap example: 

`if (permitSingle.spender != address(this)) revert IXERC20Lockbox_InvalidSpender();`

2023-08-21 15:15 UTC, 0xShaito commented on solidity/test/unit/XERC20Lockbox.t.sol
> +  function testNativeRevertsIfDepositWithPermitAllowance(uint256 _amount) public {
Can we add a happy path one that tests the correct calls into the PERMIT2 methods?
```
 PERMIT2.permit(
      _owner,
      _permit,
      signature
    );

    PERMIT2.transferFrom(_owner, address(this), _amount.toUint160(), address(ERC20));
    ```

2023-08-21 15:59 UTC, just-a-node commented on solidity/contracts/XERC20Lockbox.sol
> +
I think this condition is checked in Permit2 by way of the spender's allowance here: https://github.com/Uniswap/permit2/blob/main/src/AllowanceTransfer.sol#L84

Do you think this is still necessary?

2023-08-21 15:59 UTC, just-a-node commented on solidity/contracts/XERC20Lockbox.sol
> +   * @param _amount The amount of tokens to deposit
👍

2023-08-21 16:00 UTC, just-a-node commented on solidity/contracts/XERC20Lockbox.sol
> +    address _owner,
We intend to call this from a multicall contract where the `msg.sender` of the multicall call is passed through as the `_owner`.

2023-08-22 12:19 UTC, 0xShaito approved these changes

2023-08-22 12:19 UTC, 0xShaito commented on solidity/contracts/XERC20Lockbox.sol
> +
It's ok. It would just allow users to approve other contracts but it would fail if there is not enough allowance in the transferFrom

2023-08-23 11:38 UTC, merged